### ISSUE TITLE
Symbol RVAs incorrect

### ISSUE THREAD

**Issue by Decimation** [southpolenator/SharpPdb#2]
PDB symbols seem to have the incorrect RVA (or maybe the RVA is different from the one I'm expecting.)

Here is a comparison between the RVA calculated using the `dbghelp` Win32 functions and the RVA from `SharpPdb`:

PDB file: `clr.pdb`

Symbol: `g_pGCHeap`

RVA from **dbghelp**: `A17038`

RVA from **SharpPdb**: `A25A60`

**Comment by southpolenator** [comment]
SharpPdb is missing RVA translation using Omap and clr.pdb is defining Omap conversion. Hopefully next NuGet version will have this addressed. As a mitigation, you can try using [PdbFile.DbiStream.OmapFromSourceEntries](https://github.com/southpolenator/SharpPdb/blob/442be5a5368e708185661fb343603fa52b9a0eac/Source/Windows/DBI/DbiStream.cs#L367) to translate RVA.

**Comment by southpolenator** [comment]
Fixed with commit [da309aecb4a54b2fef199c6d102f70461452fbad](https://github.com/southpolenator/SharpPdb/commit/da309aecb4a54b2fef199c6d102f70461452fbad). If you need non-official Nuget that has this fix, you can find it on [AppVeyor](https://ci.appveyor.com/project/southpolenator/sharppdb/builds/24484212/artifacts). You can also use private nuget feed from AppVeyor CI builds.
